name: Sutkirt CI workflow

on:
  push:

jobs:
  build:    # job name
    runs-on: ubuntu-latest  # GitHub Runner (free)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # clone the code into a ubuntu runner

      - name: Set up Docker
        uses: docker/setup-buildx-action@v4